# Change these first
owner: EmnichtdaYT # Your GitHub organization or username, where this repository lives
repo: emnichtda-services # The name of this repository

sites:
  - name: www.emnichtda.de
    url: https://www.emnichtda.de
    maxResponseTime: 5000
  - name: matrix.emnichtda.de
    url: https://matrix.emnichtda.de/_synapse/client
    expectedStatusCodes: 404
    maxResponseTime: 1000
  - name: ptero.emnichtda.de
    url: https://ptero.emnichtda.de/api/client
    maxResponseTime: 1000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.emnichtda.de
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Emnichtda Service Status
  introTitle: "emnichtda.de status"
  introMessage: This is the status page of the emnichtda services
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
